language: php
php:
  - '7.2'

install:
  - make install

script:
  - make lint
  - make test

after_script:
  - vendor/bin/test-reporter

addons:
  code_climate:
    repo_token: a8d3a4d6cd3eb767c488e4c1bc65023425778a5d89c6171ad4f9c45c5fc9c4ea